# -*- coding: utf-8 -*-
"""retina_gnn_new_1_newalgo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OwhMXLmGXnirquLhxtZoj6n-0CUvaFqN
"""

# Commented out IPython magic to ensure Python compatibility.
 # %% [CELL 1]  Clone the Baccus lab repo for its data loader -----------------
!git clone https://github.com/baccuslab/torch-deep-retina.git
# %cd torch-deep-retina
!pip install -q -r requirements.txt
!pip install -q -e .
!pip install -q torch_geometric
# %cd ..

 # %% [CELL 2]  Imports, config, mount drive ----------------------------------
import os, h5py, numpy as np, torch
import torch.nn as nn, torch.nn.functional as F
import matplotlib.pyplot as plt
from scipy.spatial import cKDTree
from torch_geometric.data import HeteroData
from torch_geometric.loader import DataLoader
from torch_geometric.nn import HeteroConv, GraphConv

from google.colab import drive
drive.mount('/content/drive')

DATA_PATH = "/content/drive/MyDrive/Retina_Project/neural_code_Data/neural_code_data/ganglion_cell_data/15-11-21b/naturalscene.h5"
MODEL_PATH = "/content/drive/MyDrive/Retina_Project/retina_gnn_best.pth"
MODEL_PATH_POISSON = "/content/drive/MyDrive/Retina_Project/retina_gnn_poisson_only.pth"
os.makedirs(os.path.dirname(MODEL_PATH), exist_ok=True)

DEVICE      = "cuda" if torch.cuda.is_available() else "cpu"
GRID        = 50
WINDOW      = 60
MAX_FRAMES  = None
HIDDEN      = 128
N_ROUNDS    = 6
EPOCHS      = 5
BATCH       = 128
LR          = 1e-3
TRAIN_SPLIT      = "train"
TEST_SPLIT       = "test"
MAX_TRAIN_FRAMES = 120_000
SEED        = 0
rng = np.random.default_rng(SEED)
torch.manual_seed(SEED)
print("Device:", DEVICE)

 # %% [CELL 3]  Load data + select the 17 cells + Z-score ---------------------
CELLS_USED = [0, 1, 3, 5, 8, 9, 13, 14, 16, 17, 18, 20, 21, 22, 23, 24, 25]
N_CELLS = len(CELLS_USED)
N_GANG  = N_CELLS

def _load_split(split, n_max=None, stats=None):
    with h5py.File(DATA_PATH, "r") as f:
        T_full = f[split]["stimulus"].shape[0]
        n = T_full if n_max is None else min(T_full, n_max)
        s = f[split]["stimulus"][:n].astype(np.float32)
        r = f[split]["response"]["firing_rate_10ms"][CELLS_USED, :n].astype(np.float32)
    if stats is None:
        stats = (float(s.mean()), float(s.std()) + 1e-8)
    s = (s - stats[0]) / stats[1]
    return s, r, stats

stim,      resp,      STATS = _load_split(TRAIN_SPLIT, MAX_TRAIN_FRAMES)
stim_test, resp_test, _     = _load_split(TEST_SPLIT,  None, stats=STATS)

T      = stim.shape[0]
T_TEST = stim_test.shape[0]
print("TRAIN stim:", stim.shape, "resp:", resp.shape)
print("TEST  stim:", stim_test.shape, "resp:", resp_test.shape)

 # %% [CELL 4]  REAL, published RF centers (ganglion cells only) --------------
REAL_CENTERS_ROWCOL = {
    0: [16,13], 1: [20,12], 3: [19,7],  5: [19,3],  8: [21,7],
    9: [22,6],  13:[21,7],  14:[25,3],  16:[23,6],  17:[26,4],
    18:[24,6],  20:[26,7],  21:[27,9],  22:[26,9],  23:[27,11],
    24:[26,13], 25:[24,10],
}

def get_real_rf_centers(cells_used, grid=GRID):
    centers = []
    for c in cells_used:
        row, col = REAL_CENTERS_ROWCOL[c]
        x = (col + 0.5) / grid
        y = (row + 0.5) / grid
        centers.append((x, y))
    return np.array(centers, dtype=np.float32)

gang_pos = get_real_rf_centers(CELLS_USED)
print("Using REAL published RF centers (row,col -> normalized x,y):")
for c, (x, y) in zip(CELLS_USED, gang_pos):
    print(f"  Cell {c}: x={x:.3f}, y={y:.3f}")

 # %% [CELL 5]  Build the heterogeneous retinal graph -------------------------
# UPDATED (3 fixes, node/edge STRUCTURE unchanged):
#  1. Interneuron node counts now use REAL tiger salamander density ratios
#     (Yang et al., Vis Neurosci; Zhang & Wu 2009b) instead of an
#     unstated-origin "cell-count table".
#  2. Node positions generated with POISSON-DISC sampling (mosaic
#     regularity / minimum spacing) instead of jittered-grid mosaics.
#  3. Interneuron positions are CONCENTRATED around the real recorded
#     ganglion cell receptive fields (with margin), not spread uniformly
#     over the whole [0,1]x[0,1] field where no ganglion cell looks.
print("gang_pos right before edge-building:", gang_pos)

N_PHOTO = 49               # 2.877 * 14  -> 40   (was 625; now a coarse mosaic)
N_HORIZ = 6               # 0.372 * 14  -> 5
N_BIPO  = 41            # 2.433 * 14  -> 34
N_AMAC  = 18               # 1.042 * 14  -> 15
N_GANG  = N_CELLS
print(f"Node counts (species-correct ratios): photo={N_PHOTO} horiz={N_HORIZ} bipo={N_BIPO} amac={N_AMAC} gang={N_GANG}")

MARGIN = 0.15
x_min, x_max = float(gang_pos[:,0].min() - MARGIN), float(gang_pos[:,0].max() + MARGIN)
y_min, y_max = float(gang_pos[:,1].min() - MARGIN), float(gang_pos[:,1].max() + MARGIN)
x_min, x_max = max(0.0, x_min), min(1.0, x_max)
y_min, y_max = max(0.0, y_min), min(1.0, y_max)
REGION = (x_min, y_min, x_max, y_max)
print(f"Interneuron placement region (concentrated around real RF centers): {REGION}")

def poisson_disc_sample(n_target, region=(0, 0, 1, 1), seed=0, k=30):
    rgen = np.random.default_rng(seed)
    xmin, ymin, xmax, ymax = region
    area = (xmax - xmin) * (ymax - ymin)

    def sample_with_radius(min_dist):
        cell_size = min_dist / np.sqrt(2)
        grid_w = int(np.ceil((xmax - xmin) / cell_size)) + 1
        grid_h = int(np.ceil((ymax - ymin) / cell_size)) + 1
        grid = -np.ones((grid_w, grid_h), dtype=int)
        points, active = [], []

        def grid_coords(p):
            return int((p[0]-xmin)/cell_size), int((p[1]-ymin)/cell_size)

        p0 = (rgen.uniform(xmin, xmax), rgen.uniform(ymin, ymax))
        points.append(p0); active.append(0)
        gx, gy = grid_coords(p0); grid[gx, gy] = 0

        while active:
            idx = active[rgen.integers(len(active))]
            base = points[idx]
            found = False
            for _ in range(k):
                ang = rgen.uniform(0, 2*np.pi)
                rad = rgen.uniform(min_dist, 2*min_dist)
                cand = (base[0] + rad*np.cos(ang), base[1] + rad*np.sin(ang))
                if not (xmin <= cand[0] < xmax and ymin <= cand[1] < ymax):
                    continue
                gx, gy = grid_coords(cand)
                ok = True
                for ix in range(max(0,gx-2), min(grid_w,gx+3)):
                    for iy in range(max(0,gy-2), min(grid_h,gy+3)):
                        j = grid[ix, iy]
                        if j != -1:
                            d = np.hypot(points[j][0]-cand[0], points[j][1]-cand[1])
                            if d < min_dist:
                                ok = False; break
                    if not ok: break
                if ok:
                    points.append(cand); active.append(len(points)-1)
                    grid[gx, gy] = len(points)-1
                    found = True
            if not found:
                active.remove(idx)
        return np.array(points, dtype=np.float32)

    lo, hi = 0.001, np.sqrt(area)
    best = None
    for _ in range(15):
        mid = (lo + hi) / 2
        pts = sample_with_radius(mid)
        if best is None or abs(len(pts) - n_target) < abs(len(best) - n_target):
            best = pts
        if len(pts) > n_target:
            lo = mid
        else:
            hi = mid

    if len(best) >= n_target:
        idx = rgen.choice(len(best), n_target, replace=False)
        return best[idx]
    else:
        pad_idx = rgen.choice(len(best), n_target - len(best), replace=True)
        pad = best[pad_idx] + rgen.normal(0, 0.01, (len(pad_idx), 2))
        return np.clip(np.vstack([best, pad]), [xmin, ymin], [xmax, ymax]).astype(np.float32)

photo_pos = poisson_disc_sample(N_PHOTO, region=REGION, seed=0)
horiz_pos = poisson_disc_sample(N_HORIZ, region=REGION, seed=1)
bipo_pos  = poisson_disc_sample(N_BIPO,  region=REGION, seed=2)
amac_pos  = poisson_disc_sample(N_AMAC,  region=REGION, seed=3)

def radius_edges(src_pos, dst_pos, radius, max_k=None):
    tree = cKDTree(src_pos)
    rows, cols, dist = [], [], []
    for j, p in enumerate(dst_pos):
        idx = tree.query_ball_point(p, radius)
        if not idx:
            idx = [int(tree.query(p, 1)[1])]
        if max_k and len(idx) > max_k:
            d = np.linalg.norm(src_pos[idx] - p, axis=1)
            idx = list(np.array(idx)[np.argsort(d)[:max_k]])
        for i in idx:
            rows.append(i); cols.append(j)
            dist.append(float(np.linalg.norm(src_pos[i] - p)))
    cols = np.asarray(cols); d = np.asarray(dist)
    sigma = radius / 2 + 1e-9
    w = np.exp(-(d ** 2) / (2 * sigma ** 2))
    denom = np.zeros(len(dst_pos)); np.add.at(denom, cols, w)
    w = w / (denom[cols] + 1e-9)
    ei = torch.tensor(np.array([rows, cols]), dtype=torch.long)
    return ei, torch.tensor(w, dtype=torch.float)

_specs = {
    ('photoreceptor', 'p2b', 'bipolar'):      (photo_pos, bipo_pos,  0.07, None),
    ('photoreceptor', 'p2h', 'horizontal'):   (photo_pos, horiz_pos, 0.22, 60),
    ('horizontal',    'h2p', 'photoreceptor'):(horiz_pos, photo_pos, 0.22, 20),
    ('bipolar',       'b2a', 'amacrine'):      (bipo_pos,  amac_pos,  0.07, None),
    ('amacrine',      'a2b', 'bipolar'):       (amac_pos,  bipo_pos,  0.10, None),
}
edge_index_dict, edge_weight_dict = {}, {}
for rel, (sp, dp, r, k) in _specs.items():
    ei, w = radius_edges(sp, dp, r, k)
    edge_index_dict[rel] = ei
    edge_weight_dict[rel] = w
    print(f"{rel[1]:>4}: {ei.shape[1]:>6} edges")

def knn_edges(src_pos, dst_pos, k):
    tree = cKDTree(src_pos)
    rows, cols, dist = [], [], []
    for j, p in enumerate(dst_pos):
        k_eff = min(k, len(src_pos))
        d, idx = tree.query(p, k=k_eff)
        idx = np.atleast_1d(idx); d = np.atleast_1d(d)
        for i, di in zip(idx, d):
            rows.append(int(i)); cols.append(j); dist.append(float(di))
    cols = np.asarray(cols); d = np.asarray(dist)
    sigma = d.mean() / 2 + 1e-9
    w = np.exp(-(d ** 2) / (2 * sigma ** 2))
    denom = np.zeros(len(dst_pos)); np.add.at(denom, cols, w)
    w = w / (denom[cols] + 1e-9)
    ei = torch.tensor(np.array([rows, cols]), dtype=torch.long)
    return ei, torch.tensor(w, dtype=torch.float)

for rel, (sp, dp, k) in {
    ('bipolar',  'b2g', 'ganglion'): (bipo_pos, gang_pos, 12),
    ('amacrine', 'a2g', 'ganglion'): (amac_pos, gang_pos, 8),
}.items():
    ei, w = knn_edges(sp, dp, k)
    edge_index_dict[rel] = ei; edge_weight_dict[rel] = w
    print(f"{rel[1]:>4}: {ei.shape[1]:>6} edges (k-NN)")

NODE_COUNTS = {'photoreceptor': N_PHOTO, 'horizontal': N_HORIZ,
               'bipolar': N_BIPO, 'amacrine': N_AMAC, 'ganglion': N_GANG}

 # %% [CELL 6]  Dataset: photoreceptor features + RF patches + targets --------
PATCH = 15; _pad = PATCH // 2
_px, _py = np.meshgrid((np.arange(GRID)+0.5)/GRID, (np.arange(GRID)+0.5)/GRID)
_pix = np.stack([_px.ravel(), _py.ravel()], 1) * GRID
_, _assign = cKDTree(photo_pos * GRID).query(_pix, k=1)
POOL = np.zeros((N_PHOTO, GRID*GRID), np.float32)
POOL[_assign, np.arange(GRID*GRID)] = 1.0
POOL /= (POOL.sum(1, keepdims=True) + 1e-9)
_centers_px = np.round(gang_pos * GRID).astype(int)

def make_pool_matrix(cell_pos, n_cells):
    _, assign = cKDTree(cell_pos * GRID).query(_pix, k=1)
    pool = np.zeros((n_cells, GRID*GRID), np.float32)
    pool[assign, np.arange(GRID*GRID)] = 1.0
    pool /= (pool.sum(1, keepdims=True) + 1e-9)
    return pool

POOL_HORIZ = make_pool_matrix(horiz_pos, N_HORIZ)
POOL_BIPO  = make_pool_matrix(bipo_pos,  N_BIPO)
POOL_AMAC  = make_pool_matrix(amac_pos,  N_AMAC)

_STIM_NODES = ['photoreceptor', 'horizontal', 'bipolar', 'amacrine']
_POOLS = {'photoreceptor': POOL, 'horizontal': POOL_HORIZ,
          'bipolar': POOL_BIPO, 'amacrine': POOL_AMAC}

def _pool_ts(P, arr, chunk=20000):
    outs = []
    for i in range(0, arr.shape[0], chunk):
        blk = arr[i:i+chunk].reshape(-1, GRID * GRID)
        outs.append((blk @ P.T).astype(np.float32))
    return np.concatenate(outs, 0).T.copy()

def precompute(arr):
    ts = {nt: _pool_ts(_POOLS[nt], arr) for nt in _STIM_NODES}
    p  = np.pad(arr, ((0, 0), (_pad, _pad), (_pad, _pad)))
    rf = np.empty((N_GANG, arr.shape[0], PATCH, PATCH), np.float32)
    for c, (cx, cy) in enumerate(_centers_px):
        rf[c] = p[:, cy:cy+PATCH, cx:cx+PATCH]
    return ts, rf

TS_TR, RF_TR = precompute(stim)
TS_TE, RF_TE = precompute(stim_test)
print("precomputed:", {k: v.shape for k, v in TS_TR.items()}, RF_TR.shape)

class RetinaGraph(torch.utils.data.Dataset):
    def __init__(self, ts, rf, resp, frames):
        self.ts, self.rf, self.resp, self.frames = ts, rf, resp, frames
    def __len__(self):
        return len(self.frames)
    def __getitem__(self, i):
        t = int(self.frames[i]); s = t - WINDOW + 1
        d = HeteroData()
        for nt in _STIM_NODES:
            d[nt].x = torch.from_numpy(self.ts[nt][:, s:t+1].copy())
        for ntype, n in NODE_COUNTS.items():
            d[ntype].nid = torch.arange(n)
        for rel, ei in edge_index_dict.items():
            d[rel].edge_index  = ei
            d[rel].edge_weight = edge_weight_dict[rel]
        d['ganglion'].rf = torch.from_numpy(self.rf[:, s:t+1].copy())
        d['ganglion'].y  = torch.from_numpy(self.resp[:, t].copy())
        d['ganglion'].x  = torch.zeros((N_GANG, 1), dtype=torch.float32)
        return d

all_frames = np.arange(WINDOW - 1, T)
BLOCK      = 2000
block_id   = np.arange(len(all_frames)) // BLOCK
val_mask   = np.isin(block_id, list(range(0, block_id.max() + 1, 10)))
train_frames, val_frames = all_frames[~val_mask], all_frames[val_mask]
test_frames  = np.arange(WINDOW - 1, T_TEST)

train_ds = RetinaGraph(TS_TR, RF_TR, resp,      train_frames)
val_ds   = RetinaGraph(TS_TR, RF_TR, resp,      val_frames)
test_ds  = RetinaGraph(TS_TE, RF_TE, resp_test, test_frames)

train_ld = DataLoader(train_ds, batch_size=128, shuffle=True, drop_last=True,
                      num_workers=2, persistent_workers=True, pin_memory=True,
                      prefetch_factor=4)
val_ld   = DataLoader(val_ds,  batch_size=128, num_workers=0)
test_ld  = DataLoader(test_ds, batch_size=128, num_workers=0)
print(f"train {len(train_ds)} | val {len(val_ds)} | test {len(test_ds)}")

 # %% [CELL 7]  Model definition -----------------------------------------------
INTERNEURONS = ['horizontal', 'bipolar', 'amacrine', 'ganglion']
STIM_NODES   = ['photoreceptor', 'horizontal', 'bipolar', 'amacrine']
RELATIONS    = list(edge_index_dict.keys())
RF_FEAT      = 64

class RetinaGNN(nn.Module):
    def __init__(self, hidden=HIDDEN, rounds=N_ROUNDS, dropout=0.1):
        super().__init__()
        self.temporal = nn.Sequential(
            nn.Conv1d(1, 16, 7, padding=3),  nn.BatchNorm1d(16), nn.ReLU(),
            nn.Conv1d(16, 16, 5, padding=2), nn.BatchNorm1d(16), nn.ReLU(),
        )
        self.node_proj = nn.ModuleDict({t: nn.Linear(16 * WINDOW, hidden) for t in STIM_NODES})
        self.emb = nn.ModuleDict({t: nn.Embedding(NODE_COUNTS[t], hidden) for t in INTERNEURONS})
        self.convs = nn.ModuleList([HeteroConv({rel: GraphConv((-1, -1), hidden) for rel in RELATIONS},
                                                aggr='sum') for _ in range(rounds)])
        self.norms = nn.ModuleList([nn.ModuleDict({t: nn.LayerNorm(hidden)
                     for t in ['photoreceptor'] + INTERNEURONS}) for _ in range(rounds)])
        self.drop = nn.Dropout(dropout)
        self.rfcnn = nn.Sequential(
            nn.Conv3d(1, 16, (7, 3, 3), padding=(3, 1, 1)),  nn.BatchNorm3d(16), nn.ReLU(),
            nn.MaxPool3d((1, 2, 2)),
            nn.Conv3d(16, 32, (5, 3, 3), padding=(2, 1, 1)), nn.BatchNorm3d(32), nn.ReLU(),
            nn.MaxPool3d((1, 2, 2)),
            nn.Conv3d(32, 32, (5, 3, 3), padding=(2, 1, 1)), nn.BatchNorm3d(32), nn.ReLU(),
            nn.AdaptiveAvgPool3d((WINDOW, 1, 1)),
        )
        self.rf_head = nn.Sequential(nn.Flatten(), nn.Linear(32 * WINDOW, RF_FEAT), nn.ReLU())
        self.readout = nn.Sequential(
            nn.Linear(hidden * rounds + RF_FEAT, hidden), nn.ReLU(), nn.Dropout(dropout))
        self.cell_w = nn.Embedding(N_GANG, hidden)
        self.cell_b = nn.Embedding(N_GANG, 1)
        nn.init.normal_(self.cell_w.weight, std=0.05)
        nn.init.constant_(self.cell_b.weight, -1.0)

    def _encode(self, x_pooled):
        return self.temporal(x_pooled.unsqueeze(1)).flatten(1)

    def forward(self, data):
        x = {}
        for t in STIM_NODES:
            feat = self.node_proj[t](self._encode(data[t].x))
            if t != 'photoreceptor':
                feat = feat + self.emb[t](data[t].nid)
            x[t] = feat
        x['ganglion'] = self.emb['ganglion'](data['ganglion'].nid)
        ei = data.edge_index_dict
        ew = {rel: data[rel].edge_weight for rel in RELATIONS}
        gang_states = []
        for conv, norm in zip(self.convs, self.norms):
            out = conv(x, ei, edge_weight_dict=ew)
            x = {k: self.drop(norm[k](F.relu(out[k] + x[k]))) for k in out}
            gang_states.append(x['ganglion'])
        g = torch.cat(gang_states, dim=-1)
        rf = data['ganglion'].rf.view(-1, 1, WINDOW, PATCH, PATCH)
        rf = self.rf_head(self.rfcnn(rf))
        h  = self.readout(torch.cat([g, rf], dim=-1))
        nid = data['ganglion'].nid
        out = (h * self.cell_w(nid)).sum(-1) + self.cell_b(nid).squeeze(-1)
        return F.softplus(out)

model = RetinaGNN().to(DEVICE)
opt = torch.optim.Adam(model.parameters(), lr=LR, weight_decay=1e-5)
loss_fn = nn.PoissonNLLLoss(log_input=False, full=False)
print(model)
 # %% [VISUALIZATION CELL] 2D locations of all retinal cell types ------------
import matplotlib.pyplot as plt

cell_types = [
    ("Photoreceptors", photo_pos),
    ("Horizontal Cells", horiz_pos),
    ("Bipolar Cells", bipo_pos),
    ("Amacrine Cells", amac_pos),
    ("Ganglion Cells", gang_pos)
]

for title, pos in cell_types:
    plt.figure(figsize=(6,6))
    plt.scatter(pos[:,0], pos[:,1], s=25, alpha=0.75, edgecolors='k', linewidths=0.3)
    plt.title(f"{title} Spatial Distribution")
    plt.xlabel("X Position")
    plt.ylabel("Y Position")
    plt.grid(alpha=0.3)
    plt.axis('equal')
    # Show the concentrated region boundary for reference
    plt.axvline(REGION[0], color='red', linestyle='--', alpha=0.3)
    plt.axvline(REGION[2], color='red', linestyle='--', alpha=0.3)
    plt.axhline(REGION[1], color='red', linestyle='--', alpha=0.3)
    plt.axhline(REGION[3], color='red', linestyle='--', alpha=0.3)
    plt.xlim(0, 1); plt.ylim(0, 1)
    plt.show()

 # %% [VISUALIZATION CELL] 3D layered retinal architecture --------------------
from mpl_toolkits.mplot3d import Axes3D
import numpy as np

fig = plt.figure(figsize=(14,10))
ax = fig.add_subplot(111, projection='3d')

layers = [
    ("Photoreceptors", photo_pos, 0, 'o'),
    ("Horizontal", horiz_pos, 2, '^'),
    ("Bipolar", bipo_pos, 4, 's'),
    ("Amacrine", amac_pos, 6, 'D'),
    ("Ganglion", gang_pos, 8, '*')
]

xx, yy = np.meshgrid(np.linspace(0, 1, 2), np.linspace(0, 1, 2))
for _, _, z, _ in layers:
    zz = np.full_like(xx, z)
    ax.plot_surface(xx, yy, zz, alpha=0.12, edgecolor='gray', linewidth=0.5, shade=False)

for name, pos, z, marker in layers:
    ax.scatter(pos[:,0], pos[:,1], np.full(len(pos), z), s=80, marker=marker,
               alpha=0.9, edgecolors='black', linewidths=0.4, label=name)

ax.set_xlabel('X Position', fontsize=12)
ax.set_ylabel('Y Position', fontsize=12)
ax.set_zlabel('Retinal Layer', fontsize=12)
ax.set_zticks([0,2,4,6,8])
ax.set_zticklabels(['Photoreceptor','Horizontal','Bipolar','Amacrine','Ganglion'])
ax.set_xlim(0,1); ax.set_ylim(0,1)
ax.view_init(elev=25, azim=130)
ax.set_title('3D Layered Retinal Architecture (Poisson-disc, region-concentrated)', fontsize=16, pad=20)
ax.legend(loc='upper left')
plt.tight_layout()
plt.show()

# #Training cell
# from torch.optim.lr_scheduler import OneCycleLR
# from tqdm.notebook import tqdm

# EPOCHS = 1
# MAX_LR = 2e-3
# CORR_W = 0.3
# sched = OneCycleLR(opt, max_lr=MAX_LR, epochs=EPOCHS,
#                    steps_per_epoch=len(train_ld), pct_start=0.25)

# def pearson_loss(pred, y):
#     p = pred.view(-1, N_CELLS); t = y.view(-1, N_CELLS)
#     p = p - p.mean(0, keepdim=True); t = t - t.mean(0, keepdim=True)
#     c = (p * t).sum(0) / (p.norm(dim=0) * t.norm(dim=0) + 1e-8)
#     return 1.0 - c.mean()

# @torch.no_grad()
# def evaluate(loader):
#     model.eval(); P, Y = [], []
#     for b in loader:
#         b = b.to(DEVICE)
#         P.append(model(b).cpu().view(-1, N_CELLS))
#         Y.append(b['ganglion'].y.cpu().view(-1, N_CELLS))
#     P, Y = torch.cat(P).numpy(), torch.cat(Y).numpy()
#     cors = [np.corrcoef(P[:, c], Y[:, c])[0, 1] for c in range(N_CELLS)]
#     return float(np.nanmean(cors)), np.array(cors)

# best_corr, best_state = -1.0, None
# model.load_state_dict(torch.load(MODEL_PATH))
# for ep in range(1, EPOCHS + 1):
#     model.train(); tot = 0.0
#     for b in tqdm(train_ld, desc=f"epoch {ep}"):
#         b = b.to(DEVICE)
#         opt.zero_grad()
#         out  = model(b)
#         loss = loss_fn(out, b['ganglion'].y)
#         #+ CORR_W * pearson_loss(out, b['ganglion'].y)
#         loss.backward()
#         torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
#         opt.step(); sched.step()
#         tot += loss.item() * b.num_graphs
#     vc, _  = evaluate(val_ld)
#     tc, tp = evaluate(test_ld)
#     flag = ""
#     if vc > best_corr:
#         best_corr = vc
#         best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
#         flag = "  <-- best"
#     print(f"ep {ep:02d} | loss {tot/len(train_ds):.4f} | val {vc:.3f} | "
#           f"TEST {tc:.3f} | per-cell {np.round(tp,3)}{flag}")

# model.load_state_dict(best_state)
# tc, tp = evaluate(test_ld)
# print(f"\nFINAL TEST corr {tc:.3f} | per-cell {np.round(tp,3)}")
# torch.save(model.state_dict(), MODEL_PATH)
from torch.optim.lr_scheduler import OneCycleLR
from tqdm.notebook import tqdm
import torch.nn as nn
loss_fn = nn.PoissonNLLLoss(log_input=False)
EPOCHS = 2
MAX_LR = 2e-3
sched = OneCycleLR(opt, max_lr=MAX_LR, epochs=EPOCHS,
                   steps_per_epoch=len(train_ld), pct_start=0.25)

@torch.no_grad()
def evaluate(loader):
    model.eval(); P, Y = [], []
    for b in loader:
        b = b.to(DEVICE)
        P.append(model(b).cpu().view(-1, N_CELLS))
        Y.append(b['ganglion'].y.cpu().view(-1, N_CELLS))
    P, Y = torch.cat(P).numpy(), torch.cat(Y).numpy()
    cors = [np.corrcoef(P[:, c], Y[:, c])[0, 1] for c in range(N_CELLS)]
    return float(np.nanmean(cors)), np.array(cors)

best_corr, best_state = -1.0, None
for ep in range(1, EPOCHS + 1):
    model.train(); tot = 0.0
    for b in tqdm(train_ld, desc=f"epoch {ep}"):
        b = b.to(DEVICE)
        opt.zero_grad()
        out  = model(b)
        loss = loss_fn(out, b['ganglion'].y)          # <-- Poisson only, no Pearson term
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
        opt.step(); sched.step()
        tot += loss.item() * b.num_graphs
    vc, _  = evaluate(val_ld)
    tc, tp = evaluate(test_ld)
    flag = ""
    if vc > best_corr:
        best_corr = vc
        best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}
        flag = "  <-- best"
    print(f"ep {ep:02d} | loss {tot/len(train_ds):.4f} | val {vc:.3f} | "
          f"TEST {tc:.3f} | per-cell {np.round(tp,3)}{flag}")

model.load_state_dict(best_state)
tc, tp = evaluate(test_ld)
print(f"\nFINAL TEST corr (Poisson-only) {tc:.3f} | per-cell {np.round(tp,3)}")
torch.save(model.state_dict(), MODEL_PATH_POISSON)   # separate file — your 0.655 checkpoint stays untouched

# =====================================================================
# Data (grey) vs GNN Prediction (orange)
# Testing Cell
# =====================================================================

import numpy as np
import matplotlib.pyplot as plt

# -------------------------------------------------------
# Generate predictions on validation data
# -------------------------------------------------------
model.eval()
# model.load_state_dict(torch.load(MODEL_PATH, map_location=DEVICE))
model.load_state_dict(torch.load(MODEL_PATH_POISSON, map_location=DEVICE))
model.eval()
print(f"Loaded model from: {MODEL_PATH_POISSON}")
# print(f"Loaded model from: {MODEL_PATH}")
preds = []
truth = []

with torch.no_grad():
    for batch in test_ld:

        batch = batch.to(DEVICE)

        pred = model(batch).cpu().view(-1, N_CELLS).numpy()
        gt   = batch["ganglion"].y.cpu().view(-1, N_CELLS).numpy()

        preds.append(pred)
        truth.append(gt)

preds = np.concatenate(preds, axis=0)
truth = np.concatenate(truth, axis=0)

# -------------------------------------------------------
# Pearson correlation for every cell
# -------------------------------------------------------
pearsons = np.array([
    np.corrcoef(preds[:,i], truth[:,i])[0,1]
    for i in range(N_CELLS)
])

print("Per-cell Pearson:")
for i,p in enumerate(pearsons):
    print(f"Cell {CELLS_USED[i]} : {p:.3f}")

print(f"\nMean Pearson = {pearsons.mean():.3f}")

# -------------------------------------------------------
# Choose best-correlating cell
# -------------------------------------------------------
CELL_INDEX = 11
# CELL_INDEX = 7
CELL_ID = CELLS_USED[CELL_INDEX]

# -------------------------------------------------------
# Calibrate prediction for visualization only
# (does NOT change Pearson correlation)
# -------------------------------------------------------
a,b = np.polyfit(
    preds[:,CELL_INDEX],
    truth[:,CELL_INDEX],
    1
)

pred_plot = a*preds[:,CELL_INDEX] + b
true_plot = truth[:,CELL_INDEX]

# -------------------------------------------------------
# Time axis
# -------------------------------------------------------
BIN_S = 0.01          # 10 ms bins

FULL_SECONDS = 25

n_full = min(
    int(FULL_SECONDS/BIN_S),
    len(true_plot)
)

time_full = np.arange(n_full)*BIN_S

# -------------------------------------------------------
# Zoom around largest response
# -------------------------------------------------------
ZOOM_SECONDS = 4

center = np.argmax(true_plot)

half = int((ZOOM_SECONDS/2)/BIN_S)

start = max(0, center-half)

end = min(
    len(true_plot),
    start + int(ZOOM_SECONDS/BIN_S)
)

time_zoom = np.arange(start,end)*BIN_S

# -------------------------------------------------------
# Plot
# -------------------------------------------------------
fig,ax = plt.subplots(
    1,
    2,
    figsize=(16,5),
    sharey=True
)

# Full trace
ax[0].plot(
    time_full,
    true_plot[:n_full],
    color='gray',
    lw=1.3,
    label='Data'
)

ax[0].plot(
    time_full,
    pred_plot[:n_full],
    color='orange',
    lw=1.3,
    label='GNN'
)

ax[0].set_xlabel("Time (s)")
ax[0].set_ylabel("Firing Rate (Hz)")
ax[0].legend(frameon=False)
ax[0].set_title("Full Recording")
ax[0].spines['top'].set_visible(False)
ax[0].spines['right'].set_visible(False)

# Zoom
ax[1].plot(
    time_zoom,
    true_plot[start:end],
    color='gray',
    lw=1.5
)

ax[1].plot(
    time_zoom,
    pred_plot[start:end],
    color='orange',
    lw=1.5
)

ax[1].set_xlabel("Time (s)")
ax[1].set_title("Zoom")
ax[1].spines['top'].set_visible(False)
ax[1].spines['right'].set_visible(False)

plt.suptitle(
    f"Cell {CELL_ID}    Pearson r = {pearsons[CELL_INDEX]:.3f}",
    fontsize=14,
    fontweight="bold"
)

plt.tight_layout()

plt.show()
#this is for testing